# docker stack deploy -c stack.yml jupyter
# optional pgadmin container

version: "3.7"
networks:
  demo-net:
services:
  spark:
    image: ${REPO}
    container_name: spark
    ports:
    - "8888:8888/tcp"
    - "4040:4040/tcp"
    networks:
    - demo-net
    working_dir: /home/$USER/notebooks
    environment:
      CHOWN_HOME: "yes"
      GRANT_SUDO: "yes"
      NB_UID: 1000
      NB_GID: 100
      NB_USER: $USER
      NB_GROUP: staff
    user: root
    deploy:
     replicas: 1
     restart_policy:
       condition: on-failure
    volumes:
    - $PWD/notebooks:/home/$USER/notebooks

  postgres:
    image: postgres:13.1
    container_name: course-database
    ports:
      - 54320:54320
    environment:
      - POSTGRES_USER=${SOURCE_USER}
      - POSTGRES_PASSWORD=${SOURCE_PASSWORD}
      - POSTGRES_DB=${SOURCE_DB}
    networks:
    - demo-net
    deploy:
     restart_policy:
       condition: on-failure

  adminer:
    image: adminer:latest
    ports:
    - "8080:8080/tcp"
    networks:
    - demo-net
    deploy:
     restart_policy:
       condition: on-failure